apiVersion: apps/v1
kind: Deployment
metadata:
  name: deduper-deployment
  labels:
    app: deduper
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deduper
  template:
    metadata:
      labels:
        app: deduper
    spec:
      containers:
        - name: deduper
          image: jimwallet/deduper:v2
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
              name: deduper
      volumes:
        - name: config-volume
          configMap:
            name: special-config
